Update appsec-1.yaml

diff --git a/integration-i3gis/appsec-1.yaml b/integration-i3gis/appsec-1.yaml
--- a/integration-i3gis/appsec-1.yaml
+++ b/integration-i3gis/appsec-1.yaml
@@ -9,27 +9,18 @@ spec:
       script: |
         #!/bin/sh
         apt-get update && apt-get install -y curl
-        urlScan="https://api.i3gis.id/scan-svc/scan"
-        token="Bearer 6Kb03xxdXX88x6MQRj3QwZv9yQsOg/RM0xfJABSZsU+qfRLjQyJDTQTBrvWbke0lv9xwfxD1Mc3q9tGIkh8fOfTilhxB5TLowFmR3MEoxiO1hN0cCdMA5hZwHIoaRVnKoIWVrqgsOOJym5bEFnBPww=="
-        project_id=5
-
-        responseScan=$(curl -s -w '\n%{response_code}' --location -g --request POST $urlScan \
-                        --header 'Content-Type: application/json' \
-                        --header "Authorization: $token" \
-                        -d "{\"project_id\":$project_id}")
-
-        codeScan=$(echo "$responseScan" | tail -n1)
-
-        echo "HTTP response status code: $codeScan"
-
-        if [ "$codeScan" != "200" ]; then
-            echo "Response: $responseScan"
-            exit 1
+        echo "Scanning project 123 with i3gis..."
+        scanResponse=$(curl --write-out '%{http_code}' --request POST -sL --url 'https://api.i3gis.id/scan-svc/scan' --header 'Content-Type: application/json' --header 'Authorization: Bearer zOYFAF34oZRjPVMVC666kuEXJoB2qFzyVanntw4Hd6PjmmzT827vPhP7q1VGfWgP6sGdKwuPXUyWqe/+V5nVfAMCSCaaVreCBJmkXCQh8sWZwPMCEl2E4QMPJSnlhUFaVpgbZ310Bd9YyA9ev4tptw==' --data '{"project_id":5}')
+        scanCode=$(echo $scanResponse | grep -o ...$)
+        echo "HTTP response status code: $scanCode"
+        if [ $scanCode = "200" ]; then
+          echo "Scan project 123 with i3gis..."
         else
-            echo "Scan project $project_id with i3gis..."
+          echo "Response: $scanResponse"
+          echo "Build failed because scan was not successful..."
+          exit 1
         fi
-
-        echo "Scan project $project_id with i3gis is starting..."
+        echo "Scan project 123 with i3gis is starting..."
 
     - name: i3gis-scan-status
       image: debian
@@ -38,30 +29,19 @@ spec:
         apt-get update && apt-get install -y curl
         echo "Get scan status..."
         status_running=true
-    
-        while $status_running; do
-            sleep 5
-            echo "Scan still running..."
-            urlStatus="https://api.i3gis.id/scan-svc/scan/5"
-            token="Bearer kRCNeHC+np9t0Gjs0S049nHfX+fHBjvVzbUgFmgXjsBRZe8oON2jDvdACG/PFENAvtBpGS4sG1NfNjbL0QLCK6c114sIODEv6Dv8uxYXUWyPaNgy1RXclvlPA1/uv/ukUPcAboVW+LGCNtNaq2Bc8A=="
-    
-            responseStatus=$(curl -s -w '\n%{response_code}' --location -g --request GET $urlStatus \
-                            --header 'Content-Type: application/json' \
-                            --header "Authorization: $token")
-    
-            codeStatus=$(echo "$responseStatus" | tail -n1)
-    
-            echo "HTTP response status code: $codeStatus"
-    
-            if [ "$codeStatus" != "200" ] && [ "$codeStatus" != "404" ]; then
-                echo "Value of codeStatus is: $codeStatus"
-                echo "Response: $responseStatus"
-                exit 1
-            fi
-    
-            if [ "$codeStatus" == "404" ]; then
-                break
-            fi
+        while [ "$status_running" = true ]; do
+          sleep 5
+          echo "Scan still running..."
+          checkResponse=$(curl --write-out ''%{http_code}'' --request GET -sL --url 'https://api.i3gis.id/scan-svc/scan/5' --header 'Content-Type: application/json' --header 'Authorization: Bearer zOYFAF34oZRjPVMVC666kuEXJoB2qFzyVanntw4Hd6PjmmzT827vPhP7q1VGfWgP6sGdKwuPXUyWqe/+V5nVfAMCSCaaVreCBJmkXCQh8sWZwPMCEl2E4QMPJSnlhUFaVpgbZ310Bd9YyA9ev4tptw==')
+          checkCode=$(echo $checkResponse | grep -o ...$)
+          echo "HTTP response status code: $checkCode"
+          if [ $checkCode != "200" ] && [ $checkCode != "404" ]; then
+            echo "Response: $checkResponse"
+            echo "Scan failed..."
+            exit 1
+          fi
+          if [ $checkCode = "404" ]; then
+            echo "Scan finished..."
+            status_running=false
+          fi
         done
-    
-        echo "Scan finished..."
