Update consec.yaml

diff --git a/integration-i3gis/consec.yaml b/integration-i3gis/consec.yaml
--- a/integration-i3gis/consec.yaml
+++ b/integration-i3gis/consec.yaml
@@ -12,7 +12,7 @@ spec:
     - name: consec-scan
       image: debian
       script: |
-        apt-get update && apt-get install -y curl
+        apt install -y curl
         scanResponse=$(curl --write-out '%{http_code}' --request POST -sL --url '/api/v1/integration/image/scan' --header 'Content-Type: application/json' --header 'Authorization: Bearer YOUR_AUTH_TOKEN_HERE' --data '{"container_project_id":2,"image_name":"nginx","image_tag":"1.0.0"}')
         scanCode=$(echo $scanResponse | grep -o ...$)
         echo "HTTP response status code: $scanCode"
@@ -28,12 +28,22 @@ spec:
     - name: consec-scan-status
       image: debian
       script: |
-        apt-get update && apt-get install -y curl
+        apt install -y curl
         echo "Get scan status..."
         status_running=true
         while [ "$status_running" = true ]; do
           sleep 5
           echo "Scan still running..."
-          # Add your logic to check scan status
-          # ...
+          checkResponse=$(curl --write-out ''%{http_code}'' --request GET -sL --url '/api/v1/integration/image/${{needs.i3gis-job.outputs.I3GIS_IMAGE_ID}}' --header 'Content-Type: application/json' --header 'Authorization: Bearer NKIXHVYgwWwkqn5hPqYxoSTGxqWdGW3ZlmvVJFuerjOD78BwfGFLcuft5RrivQQfJIwKXFpXrUyfjNgR3BW83RtP7wXW7AIal71dK98vkmvf8qphcnq+tk5iUxtEB8P94wpD2dJuKVvd+ciS6BUo6z1m2S9oARp2')
+          checkCode=$(echo $checkResponse | grep -o ...$)
+          echo "HTTP response status code: $checkCode"
+          if [ $checkCode != "201" ] && [ $checkCode != "404" ]; then
+            echo "Response: $checkResponse"
+            echo "Scan failed..."
+            exit 1
+          fi
+          if [ $checkCode = "404" ]; then
+            echo "Scan finished..."
+            status_running=false
+          fi
         done
